name: Gauge Pipeline

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Gauge and Python plugin
        run: |
          wget -qO - https://downloads.gauge.org/stable | sudo bash
          gauge install python
          gauge install html-report

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          gauge install python
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: gauge run business_functions/specs/

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: reports/
