name: Gauge Pipeline

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install and run
        run: |
          curl -SsL https://downloads.gauge.org/stable | run-as root bash
          gauge install python
          gauge install html-report
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          gauge run business_functions/specs/ --simple-console --simple-html-report --simple-csv-report --simple-json-report
        working-directory: ${{ github.workspace }}

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: reports/
